---
project_name: winkube

release:
  github:
    owner: winkube
    name: winkube

builds:
  - binary: winkube
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/winkube/
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - format: zip
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc

