name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        go: ["1.17.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go }}
    - name: Build
      run: go build -ldflags -s -w -extldflags "-static -Wl,--fatal-warnings" -o bin/winkube.exe -v ./...
  
    - run: "go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.0.0
      with:
        version: "2021.1.2"
        install-go: false
        cache-key: ${{ matrix.go }}
