name: Continous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        go: ["1.17.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go }}
    - name: Install Mage
      run: |
        go install github.com/magefile/mage
    - name: Continuous Integration
      run: mage ci
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - uses: dominikh/staticcheck-action@v1.0.0
      with:
        version: "2021.1.2"
        install-go: false
        cache-key: ${{ matrix.go }}